### ISSUE TITLE
Error when inserting reset actions in Mautic 2.10

### ISSUE THREAD

**Issue by scmoral** [thirdset/ThirdSetMauticResetBundle#3]
I've been trying to introduce reset actions to my campaign in a Mautic 2.10 version and got this kind of errors:

`[2017-09-12 17:20:18] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Form\Exception\TransformationFailedException: "Unable to transform value for property path "[add_tags]": Tags for "Array" does not exist!" at /var/www/mautic_2.10/vendor/symfony/form/Form.php line 1086 {"exception":"[object] (Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Unable to transform value for property path \"[add_tags]\": Tags for \"Array\" does not exist! at /var/www/mautic_2.10/vendor/symfony/form/Form.php:1086, Symfony\\Component\\Form\\Exception\\TransformationFailedException(code: 0): Tags for \"Array\" does not exist! at /var/www/mautic_2.10/app/bundles/LeadBundle/Form/DataTransformer/TagEntityModelTransformer.php:134)"} []`

The effect is as follows:
- Insert several reset actions and saving themo ne by one in the campaign editor with "reset_1" tag
- At a certain moment, when opening several times the campaign editor for that campaign, the reset actions are blanked.
- Try to make this operation several times and allways getting the same result.

I have tried to save with the new "Apply" button that Mautic 2.10 provides in the campaign editor and with the usual way (making the actions, closing editor and saving & applying changes) ... always the same result.

I know that the plugin has been tested until V 2.9.2 of Mautic but maybe this error is helpful for your next version of this "so-much-needed" plugin.

Best regards.

**Comment by collinkrawll** [comment]
Tagging a contact via a campaign action is part of Mautic's core functionality. This plugin doesn't make any modifications to that. All that this plugin does is recognize tags that are of a particular format and allow you to delete the history of contacts that have a matching tag (via a Command).  So I feel that your issue is likely elsewhere. 

You could try uninstalling the plugin and then see if you continue to have the issue. If so, you could post the issue to the main [Mautic](https://github.com/mautic/mautic/issues) repo. 

I also found this open issue that might be related:

https://github.com/mautic/mautic/issues/4195

**Comment by scmoral** [comment]
Collin.

Thank you for your quick answer.
Yes, you are right indeed. It seem to be a Mautic error
